// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB04MsDBkcqp6FJselgS8EQMWZJqUmQ_1w',
    appId: '1:1079483507451:web:79973fdb969d609de5c65e',
    messagingSenderId: '1079483507451',
    projectId: 'nvert-1ec6c',
    authDomain: 'nvert-1ec6c.firebaseapp.com',
    databaseURL: 'https://nvert-1ec6c-default-rtdb.firebaseio.com',
    storageBucket: 'nvert-1ec6c.firebasestorage.app',
    measurementId: 'G-YWF18J8PQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi-VvMQyTS0hJq1Fpmj7ImP_Pvlqe4gkw',
    appId: '1:1079483507451:android:b3d67058209630bae5c65e',
    messagingSenderId: '1079483507451',
    projectId: 'nvert-1ec6c',
    databaseURL: 'https://nvert-1ec6c-default-rtdb.firebaseio.com',
    storageBucket: 'nvert-1ec6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDahv_eQofRvoRHORGC_O3WWa-Zut4mm4o',
    appId: '1:1079483507451:ios:c0d2988d221d56fbe5c65e',
    messagingSenderId: '1079483507451',
    projectId: 'nvert-1ec6c',
    databaseURL: 'https://nvert-1ec6c-default-rtdb.firebaseio.com',
    storageBucket: 'nvert-1ec6c.firebasestorage.app',
    iosBundleId: 'com.example.invert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDahv_eQofRvoRHORGC_O3WWa-Zut4mm4o',
    appId: '1:1079483507451:ios:c0d2988d221d56fbe5c65e',
    messagingSenderId: '1079483507451',
    projectId: 'nvert-1ec6c',
    databaseURL: 'https://nvert-1ec6c-default-rtdb.firebaseio.com',
    storageBucket: 'nvert-1ec6c.firebasestorage.app',
    iosBundleId: 'com.example.invert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB04MsDBkcqp6FJselgS8EQMWZJqUmQ_1w',
    appId: '1:1079483507451:web:d7d9d87dc66691b2e5c65e',
    messagingSenderId: '1079483507451',
    projectId: 'nvert-1ec6c',
    authDomain: 'nvert-1ec6c.firebaseapp.com',
    databaseURL: 'https://nvert-1ec6c-default-rtdb.firebaseio.com',
    storageBucket: 'nvert-1ec6c.firebasestorage.app',
    measurementId: 'G-JE3NNE3LZP',
  );
}
